
name: Generate and publish documentation

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v1
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
      if: runner.os != 'Windows'
    - name: Setup Nim (if necessary)
      uses: jiro4989/setup-nim-action@v1 # default: stable

    - name: Clean up old documentation
      run: rm -rf ./htmldocs
    - name: Generate documentation
      run: |
        nimble develop -y
        rm -rf ./htmldocs
        nim doc --project --index:on --outdir:htmldocs src/strides.nim
    - name: Publish documentation to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./htmldocs
